'use client';

import RepoTable from './SubjectsTable';
import { Column, Grid } from '@carbon/react';

const headers = [
  {
    key: 'subject',
    header: 'Subject',
  },
  {
    key: 'reference',
    header: 'Reference',
  },
  {
    key: 'type',
    header: 'Type',
  },
  {
    key: 'ects',
    header: 'ECTS',
  },
  {
    key: 'semester',
    header: 'Semester',
  },
  {
    key: 'intensification',
    header: 'Intensification',
  },
];

const rows = [
  {
    id: '1',
    subject: 'TECNOLOGIAS EMERGENTES Y OPORTUNIDADES DE NEGOCIOS',
    reference: '103000605',
    type: 'Obligatoria',
    ects: '3.00',
    semester: '1',
    intensification: 'Dirección y Gestión',
  },
  {
    id: '2',
    subject: 'SISTEMAS INTELIGENTES (INTELLIGENT SYSTEMS)',
    reference: '103000606',
    type: 'Obligatoria',
    ects: '4.50',
    semester: '1',
    intensification: 'Tecnologías Informáticas (48 ECTS)',
  },
  {
    id: '3',
    subject: 'ANÁLISIS INTELIGENTE DE DATOS (INTELLIGENT DATA ANALYSIS)',
    reference: '103000607',
    type: 'Obligatoria',
    ects: '4.50',
    semester: '1',
    intensification: 'Tecnologías Informáticas (48 ECTS)',
  },
  {
    id: '4',
    subject: 'SISTEMAS INTERACTIVOS',
    reference: '103000608',
    type: 'Obligatoria',
    ects: '4.50',
    semester: '1',
    intensification: 'Tecnologías Informáticas (48 ECTS)',
  },
  {
    id: '5',
    subject: 'SISTEMAS EMPOTRADOS Y UBICUOS',
    reference: '103000609',
    type: 'Obligatoria',
    ects: '4.50',
    semester: '1',
    intensification: 'Tecnologías Informáticas (48 ECTS)',
  },
  {
    id: '6',
    subject: 'INGENIERIA DEL PROCESADO DE LOS DATOS (DATA PROCESSES)',
    reference: '103000610',
    type: 'Obligatoria',
    ects: '4.50',
    semester: '1',
    intensification: 'Tecnologías Informáticas (48 ECTS)',
  },
  {
    id: '7',
    subject: 'PROFUNDIZACIÓN EN INGENIERÍA DEL SOFTWARE',
    reference: '103000611',
    type: 'Obligatoria',
    ects: '3.00',
    semester: '1',
    intensification: 'Tecnologías Informáticas (48 ECTS)',
  },
  {
    id: '8',
    subject: 'PLANIFICACIÓN ESTRATÉGICA',
    reference: '103000621',
    type: 'Obligatoria',
    ects: '4.50',
    semester: '2',
    intensification: 'Dirección y Gestión (12 ECTS)',
  },
  {
    id: '9',
    subject: 'DIRECCIÓN DE PROYECTOS',
    reference: '103000627',
    type: 'Obligatoria',
    ects: '4.50',
    semester: '2',
    intensification: 'Dirección y Gestión (12 ECTS)',
  },
  {
    id: '10',
    subject: 'GRÁFICOS POR ORDENADOR',
    reference: '103000622',
    type: 'Obligatoria',
    ects: '3.00',
    semester: '2',
    intensification: 'Tecnologías Informáticas (48 ECTS)',
  },
  {
    id: '11',
    subject: 'EVALUACIÓN Y ASEGURAMIENTO DE SISTEMAS DE INFORMACIÓN',
    reference: '103000623',
    type: 'Obligatoria',
    ects: '4.50',
    semester: '2',
    intensification: 'Tecnologías Informáticas (48 ECTS)',
  },
  {
    id: '12',
    subject: 'DISEÑO Y SEGURIDAD DE REDES',
    reference: '103000624',
    type: 'Obligatoria',
    ects: '6.00',
    semester: '2',
    intensification: 'Tecnologías Informáticas (48 ECTS)',
  },
  {
    id: '13',
    subject: 'SISTEMAS OPERATIVOS AVANZADOS',
    reference: '103000625',
    type: 'Obligatoria',
    ects: '3.00',
    semester: '2',
    intensification: 'Tecnologías Informáticas (48 ECTS)',
  },
  {
    id: '14',
    subject: 'COMPUTACIÓN PARA CIENCIAS E INGENIERÍA',
    reference: '103000626',
    type: 'Obligatoria',
    ects: '6.00',
    semester: '2',
    intensification: 'Tecnologías Informáticas (48 ECTS)',
  },
  {
    id: '15',
    subject: 'PROGRAMACIÓN PARALELA Y DISTRIBUIDA',
    reference: '103000637',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: 'Intensificación en Informática (30 ECTS)',
  },
  {
    id: '16',
    subject: 'DESARROLLO DE SOFTWARE DE SEGURIDAD EN RED',
    reference: '103000817',
    type: 'Optativa',
    ects: '6.00',
    semester: '3',
    intensification: 'Intensificación en Informática (30 ECTS)',
  },
  {
    id: '17',
    subject: 'DISEÑO DE ECOSISTEMAS PARA CLOUD COMPUTING Y BIG DATA',
    reference: '103000639',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: 'Intensificación en Informática (30 ECTS)',
  },
  {
    id: '18',
    subject: 'BIG DATA',
    reference: '103001020',
    type: 'Optativa',
    ects: '3.00',
    semester: '3',
    intensification: 'Intensificación en Informática (30 ECTS)',
  },
  {
    id: '19',
    subject: 'DATA VISUALIZATION',
    reference: '103001021',
    type: 'Optativa',
    ects: '3.00',
    semester: '3',
    intensification: '',
  },
  {
    id: '20',
    subject: 'DESARROLLO DE APLICACIONES MÓVILES',
    reference: '103000642',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: '',
  },
  {
    id: '21',
    subject: 'INFRAESTRUCTURAS DE DATOS ESPACIALES (IDES)',
    reference: '103000656',
    type: 'Optativa',
    ects: '6.00',
    semester: '3',
    intensification: 'Intensificación en Informática (30 ECTS)',
  },
  {
    id: '22',
    subject: 'GOBERNANZA Y GESTIÓN DE TI',
    reference: '103000643',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: 'Intensificación en Informática (30 ECTS)',
  },
  {
    id: '23',
    subject: 'HABILIDADES PERSONALES DE RELACIÓN Y COMUNICACIÓN',
    reference: '103000644',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: 'Intensificación en Informática (30 ECTS)',
  },
  {
    id: '24',
    subject: 'GESTIÓN DE LA INNOVACIÓN',
    reference: '103000645',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: 'Intensificación en Informática (30 ECTS)',
  },
  {
    id: '25',
    subject: 'DIRECCIÓN FINANCIERA',
    reference: '103000646',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: 'Intensificación en Informática (30 ECTS)',
  },
  {
    id: '26',
    subject: 'NEGOCIO EN TI',
    reference: '103000647',
    type: 'Optativa',
    ects: '6.00',
    semester: '3',
    intensification: 'Intensificación en Informática (30 ECTS)',
  },
  {
    id: '27',
    subject: 'DIRECCIÓN DE EMPRESAS DE TI',
    reference: '103000648',
    type: 'Optativa',
    ects: '6.00',
    semester: '3',
    intensification: 'Intensificación en Informática (30 ECTS)',
  },
  {
    id: '28',
    subject: 'COMPUTACIÓN SOCIAL Y SISTEMAS MULTIAGENTE',
    reference: '103000650',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: 'Inteligencia Artificial (30 ECTS)',
  },
  {
    id: '29',
    subject: 'SOFT COMPUTING',
    reference: '103000651',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: 'Inteligencia Artificial (30 ECTS)',
  },
  {
    id: '30',
    subject: 'MINERÍA DE MODELOS PARA LA TOMA DE DECISIONES',
    reference: '103000652',
    type: 'Optativa',
    ects: '6.00',
    semester: '3',
    intensification: 'Inteligencia Artificial (30 ECTS)',
  },
  {
    id: '31',
    subject: 'RECUPERACIÓN E INTEGRACIÓN DE INFORMACIÓN',
    reference: '103000653',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: 'Inteligencia Artificial (30 ECTS)',
  },
  {
    id: '32',
    subject: 'INGENIERÍA LINGÜÍSTICA',
    reference: '103000654',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: 'Inteligencia Artificial (30 ECTS)',
  },
  {
    id: '33',
    subject: 'ROBÓTICA',
    reference: '103000655',
    type: 'Optativa',
    ects: '6.00',
    semester: '3',
    intensification: 'Inteligencia Artificial (30 ECTS)',
  },
  {
    id: '34',
    subject: 'DATOS ABIERTOS Y GRAFOS DE CONOCIMIENTO (OPEN DATA AND KNOWLEDGE GRAPHS)',
    reference: '103000924',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: 'Inteligencia Artificial (30 ECTS)',
  },
  {
    id: '35',
    subject: 'FRACTALES, MODELOS Y APLICACIONES',
    reference: '103000676',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: 'Computación Científica (30 ECTS)',
  },
  {
    id: '36',
    subject: 'COMPUTACIÓN NUMÉRICA',
    reference: '103000677',
    type: 'Optativa',
    ects: '6.00',
    semester: '3',
    intensification: 'Computación Científica (30 ECTS)',
  },
  {
    id: '37',
    subject: 'GEOMETRÍA COMPUTACIONAL',
    reference: '103000678',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: 'Computación Científica (30 ECTS)',
  },
  {
    id: '38',
    subject: 'TÉCNICAS DE OPTIMIZACIÓN',
    reference: '103000679',
    type: 'Optativa',
    ects: '4.50',
    semester: '3',
    intensification: 'Computación Científica (30 ECTS)',
  },
  {
    id: '39',
    subject: 'ACCESSIBLE DESIGN AND ASSISTIVE PRODUCTS',
    reference: '103001037',
    type: 'Optativa',
    ects: '9.00',
    semester: '3',
    intensification: 'Interacción Persona Ordenador (30 ECTS)',
  },
  {
    id: '40',
    subject: 'ESTUDIO PRÁCTICO',
    reference: '103000628',
    type: 'Obligatoria',
    ects: '12.00',
    semester: '4',
    intensification: '',
  },
  {
    id: '41',
    subject: 'TRABAJO FIN DE MASTER',
    reference: '103000629',
    type: 'Obligatoria',
    ects: '18.00',
    semester: '4',
    intensification: '',
  },
];


function RepoPage() {
  return (
    <Grid className="repo-page">
      <Column lg={16} md={8} sm={4} className="repo-page__r1">
        <RepoTable headers={headers} rows={rows} />
      </Column>
    </Grid>
  );
}

export default RepoPage;
